// <auto-generated />
using System;
using LegacyHealthcareFHIR.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegacyHealthcareFHIR.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930022512_initial_db_setup")]
    partial class initial_db_setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("AiConfidence")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceField")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.FhirResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FhirJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("ImportJobId");

                    b.ToTable("FhirResources");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HospitalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("HospitalKey")
                        .IsUnique();

                    b.ToTable("Hospitals");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.Import.SourceFileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ImportJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SampleRecords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportJobId")
                        .IsUnique();

                    b.ToTable("SourceFileData");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JobStage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MappingConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFileName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceTypeDetectionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("MappingConfigurationId");

                    b.HasIndex("ResourceTypeDetectionId");

                    b.HasIndex("UserId");

                    b.ToTable("ImportJobs");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.ResourceTypeDetection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AiConfidence")
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId", "SchemaFingerprint")
                        .IsUnique();

                    b.ToTable("ResourceTypeDetections");
                });

            modelBuilder.Entity("MappingConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId", "SchemaFingerprint", "ResourceType")
                        .IsUnique();

                    b.ToTable("MappingConfigurations");
                });

            modelBuilder.Entity("FieldMapping", b =>
                {
                    b.HasOne("MappingConfiguration", "MappingConfiguration")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MappingConfiguration");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.AppUser", b =>
                {
                    b.HasOne("LegacyHealthcareFHIR.Core.Models.Hospital", "Hospital")
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.FhirResource", b =>
                {
                    b.HasOne("LegacyHealthcareFHIR.Core.Models.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegacyHealthcareFHIR.Core.Models.ImportJob", null)
                        .WithMany()
                        .HasForeignKey("ImportJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegacyHealthcareFHIR.Core.Models.ImportJob", b =>
                {
                    b.HasOne("LegacyHealthcareFHIR.Core.Models.Hospital", null)
                        .WithMany()
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MappingConfiguration", "MappingConfiguration")
                        .WithMany()
                        .HasForeignKey("MappingConfigurationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegacyHealthcareFHIR.Core.Models.ResourceTypeDetection", "ResourceTypeDetection")
                        .WithMany()
                        .HasForeignKey("ResourceTypeDetectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegacyHealthcareFHIR.Core.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("MappingConfiguration");

                    b.Navigation("ResourceTypeDetection");
                });

            modelBuilder.Entity("MappingConfiguration", b =>
                {
                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
